
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Yash Goel\Downloads\New folder\dashboard_design\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("960x540")
window.configure(bg = "#F1F4F7")


canvas = Canvas(
    window,
    bg = "#F1F4F7",
    height = 540,
    width = 960,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    12.0,
    147.0,
    189.0,
    525.0,
    fill="#FCFCFC",
    outline="")

canvas.create_rectangle(
    13.0,
    9.0,
    951.0,
    139.0,
    fill="#F9F9F9",
    outline="")

canvas.create_rectangle(
    199.0,
    147.0,
    946.0,
    352.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    199.0,
    362.0,
    409.0,
    426.0,
    fill="#FCFCFC",
    outline="")

canvas.create_rectangle(
    421.0,
    362.0,
    946.0,
    525.0,
    fill="#FCFCFC",
    outline="")

canvas.create_text(
    247.0,
    367.0,
    anchor="nw",
    text="PREDICTION",
    fill="#6F6F6F",
    font=("Inter Medium", 16 * -1)
)

canvas.create_text(
    598.0,
    369.0,
    anchor="nw",
    text="DATABASE DETAILS",
    fill="#6F6F6F",
    font=("Inter Medium", 16 * -1)
)

canvas.create_rectangle(
    199.0,
    436.0,
    409.0,
    525.0,
    fill="#FCFCFC",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    552.0,
    73.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    150.0,
    73.0,
    image=image_image_2
)

canvas.create_text(
    53.0,
    155.0,
    anchor="nw",
    text="DATABASES",
    fill="#6F6F6F",
    font=("Inter Medium", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=32.0,
    y=189.0,
    width=137.0,
    height=24.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=32.0,
    y=227.0,
    width=137.0,
    height=24.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=32.0,
    y=267.0,
    width=137.0,
    height=24.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=32.0,
    y=307.0,
    width=137.0,
    height=24.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=32.0,
    y=347.0,
    width=137.0,
    height=24.0
)
window.resizable(False, False)
window.mainloop()
